# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://tjhosford.github.io/
baseurl: /
title: Tom Hosford
author: Tom Hosford
description: Personal blog and resume
avatar: headshot3.png
email: tomhosford@gmail.com
github: tjhosford # username
twitter: t__hos
instagram: t__hos
linkedin: tom-hosford-6086b319
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
